### PR TITLE
Support Ecto 2.0

### PR DESCRIPTION
**Pull request by aptinio**

### CODE REVIEW

**Comment by bcardarella** [comment]
@aptinio does this introduce breaking changes for Ecto 1.x support?

**Comment by aptinio** [comment]
@bcardarella no, it doesn't. Thanks for checking this out.

**Comment by bcardarella** [comment]
Sorry for letting this go stale. We were able to migrate: https://github.com/DockYard/valid_field/pull/19

**Comment by aptinio** [comment]
Not a problem! 👍

**Pull request closed without merging**
